name: Continuous Delivery

on:
  release:
    types: [published]

jobs:
  Publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - run: echo "Deploying to production server on branch $GITHUB_REF"