name: Continuous Delivery

on:
  release:
    types: [published]

jobs:
  Publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
    
    - name: Build and Pack
      run: |
        TAG=$(echo $GITHUB_REF | cut -c 11-)
        dotnet build src/Moschen.AwsLambdaAuthenticationHandler/Moschen.AwsLambdaAuthenticationHandler.csproj -c Release -p:Version=$TAG
        dotnet pack src/Moschen.AwsLambdaAuthenticationHandler/Moschen.AwsLambdaAuthenticationHandler.csproj -c Release --no-build -p:PackageVersion=$TAG
        dotnet nuget push Moschen.AwsLambdaAuthenticationHandler.$TAG.nupkg --skip-duplicate --api-key $NUGET_KEY
    
    - name: Publish the package to nuget.org
      run: dotnet nuget push */bin/Release/*.nupkg -k $NUGET_AUTH_TOKEN -s https://api.nuget.org/v3/index.json
      env:
        NUGET_AUTH_TOKEN: $NUGET_KEY
    
