name: Continuous Delivery

on:
  release:
    types: [published]

jobs:
  Publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Sandbox 
      run: |
        TAG=$(echo $GITHUB_REF | cut -c 11-)
        echo "Deploying to Nuget server version '$TAG'"
        dotnet build src/Moschen.AwsLambdaAuthenticationHandler/Moschen.AwsLambdaAuthenticationHandler.csproj -c Release -p:Version=$TAG
        dotnet pack src/Moschen.AwsLambdaAuthenticationHandler/Moschen.AwsLambdaAuthenticationHandler.csproj -c Release -o . --no-build -p:PackageVersion=$TAG
        dotnet nuget push Moschen.AwsLambdaAuthenticationHandler.$TAG.nupkg --skip-duplicate --api-key $NUGET_KEY --source https://api.nuget.org/v3/index.json
    
