name: Continuous Integration

on: push

jobs:
  Test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    
    - name: Test
      run: dotnet test src/Moschen.AwsLambdaAuthenticationHandler.UnitTests/Moschen.AwsLambdaAuthenticationHandler.UnitTests.csproj --collect:"XPlat Code Coverage"
    
    - name: Install ReportGenerator tool
      if: success()
      run: dotnet tool install --global dotnet-reportgenerator-globaltool --version 4.5.8
      
    - name: Create Coverage Report
      run: |
        cd src/Moschen.AwsLambdaAuthenticationHandler.UnitTests/TestResults
        cd $(ls -d */|head -n 1)
        reportgenerator "-reports:coverage.cobertura.xml" "-targetdir:coveragereport" -reporttypes:Html
    
    - name: Upload Report Results
      uses: actions/upload-artifact@v2.2.2
      with:
        name: TestResults
        path: src/Moschen.AwsLambdaAuthenticationHandler.UnitTests/TestResults
        retention-days: 1
